language: generic 
sudo: required
services:
  - docker 

before_install: 
  - docker build -t leeinjae/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true leeinjae/docker-react npm run test -- --coverage

