language: generic 
sudo: required
services:
  - docker 

before_install: 
  - docker build -t leeinjae/docker-react -f Dockerfile.dev . 

script: 
  - docker run -e CI=true leeinjae/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk 
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-367956374365"
  bucket_path: "docker-react"
  on: 
    branch: master 
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
    
  # access_key_id: $AWS_ACCESS_KEY
  # secret_access_key: $AWS_SECRET_KEY

